[profile.release]
panic = 'unwind'
split-debuginfo = "unpacked"


[workspace]
members = [
	'node',
	"pallets/proposals",
	"pallets/briefs",
	"pallets/grants",
	"pallets/crowdfunding",
	"pallets/deposits",
<<<<<<< HEAD
	"pallets/disputes",
=======
	"pallets/fellowship",
>>>>>>> 0eda93403d2da87ddbadc3c71c69044918a7cb4a
	"runtime/integration-tests",
	"runtime/imbue-kusama",
	"runtime/common",
]
