[profile.release]
panic = 'unwind'
split-debuginfo = "unpacked"


[workspace]
members = [
    'node',
	"pallets/proposals",
	"pallets/briefs",
	"pallets/grant",
	"runtime/integration-tests",
	"runtime/imbue-kusama",
	"runtime/common",
]
