[profile.release]
panic = 'unwind'
split-debuginfo = "unpacked"


[workspace]
members = [
	'node',
	"pallets/projects",
	"pallets/briefs",
	"pallets/grants",
	"pallets/crowdfunding",
	"pallets/deposits",
	"runtime/integration-tests",
	"runtime/imbue-kusama",
	"runtime/common",
]
