[package]
name = "runtime-integration-tests"
version = "0.1.0"
authors = ["Imbue <contact@imbue.network>"]
edition = "2021"
license = "LGPL-3.0"
homepage = "https://imbue.network"
repository = "https://github.com/ImbueNetwork/imbue"


[dependencies]

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# Polkadot
kusama-runtime = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
polkadot-primitives = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17" }

# Cumulus
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17" }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17" }

# Orml pallets
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "master" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "master" }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "master" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "master" }

# Misc
xcm-emulator = { git = "https://github.com/shaunxw/xcm-simulator", rev="24ccbce563d1f99019b4cdfa2f3af4e99bac0dfc" }

# Local
common-runtime = { path = "../common" }
development-runtime = { path = "../development" }
common-traits = { path = "../../libs/common-traits", default-features = false }
common-types = { path = "../../libs/common-types", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "release-v0.9.17" }