[package]
name = "pallet-proposals-rpc-runtime-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/api" }
pallet-proposals = {default-features = false, path = "../../../proposals" }
