version: "3.2"
services:
  launch:
      container_name: launch
      image: samelamin/imbue:0.9.20
      ports:
        - "30330-31345:30330-31345"
        - "9900-9990:9900-9990"
      command: bash -c "cp /polkadot-launch/imbueLaunchConfig.js /launch/;rm rococo-*; yarn start imbueLaunchConfig.js"
      volumes:
        - ./polkadot-launch/:/polkadot-launch/
      environment:
        NODE_KEY_ALICE: ${NODE_KEY_ALICE}
        NODE_KEY_BOB: ${NODE_KEY_BOB}
  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"