version: "3.2"
services:
  imbue-1:
    container_name: imbue-1
    image: samelamin/imbue:0.9.26
    ports:
      - "9615:9615"
      - "9616:9616"
      - "9942:9942"
      - "9980:9930"
      - "30333:30333"
      - "30334:30334"
    environment:
      NODE_KEY: ${NODE_KEY}
      IP_ADDRESS: ${IP_ADDRESS}
    command: bash -c "wget https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/imbue-rococo-spec.json;sed '/'"$IP_ADDRESS"'*/ d' imbue-rococo-spec.json >> fixed_spec; mv fixed_spec imbue-rococo-spec.json; /imbue --collator --allow-private-ipv4 --unsafe-ws-external --rpc-cors=all --rpc-external --rpc-methods=Unsafe -d /cumulus_parachain/imbue-1 --name imbue-collator-1 --node-key=$NODE_KEY --ws-port 9942 --rpc-port 9930 --parachain-id 2121 --chain imbue-rococo-spec.json --rpc-max-request-size=99999 --ws-max-connections=200 --execution=wasm --prometheus-external --port 30333 -- --port 30334 --chain rococo --sync fast-unsafe --execution=native-else-wasm --pruning=256"
    volumes:
      - ./imbue_db/cumulus_parachain_1:/cumulus_parachain/
  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"