version: "3.2"
services:
  imbue-1:
    container_name: imbue-1
    image: samelamin/imbue:release-polkadot-v1.1.0
    ports:
      - "9615:9615"
      - "9616:9616"
      - "9942:9942"
      - "9980:9930"
      - "30333:30333"
      - "30334:30334"
    command: bash -c "wget https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/chain-specs/kusama.json;wget https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/genesis/imbue-kusama-spec.json;/imbue --collator --allow-private-ipv4 --unsafe-rpc-external --rpc-cors=all --rpc-external --rpc-methods=Unsafe -d /cumulus_parachain/imbue-1 --name imbue-collator-1 --rpc-port 9942  --parachain-id 2121 --chain imbue-kusama-spec.json --rpc-max-request-size=99999 --rpc-max-connections=5000 --prometheus-external --port 30333 --pruning archive -- --port 30334 --chain kusama.json --sync warp"
    volumes:
      - ./imbue_db/cumulus_parachain_1:/cumulus_parachain/
  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"
