version: "3.2"
services:
  launch:
      container_name: launch
      image: samelamin/imbue:0.9.18
      ports:
        - "30330-30345:30330-30345"
        - "9900-9960:9900-9960"
      command: bash -c "cp /polkadot-launch/imbueLaunchConfig.js /launch/; yarn start imbueLaunchConfig.js"
      volumes:
        - ./polkadot-launch/:/polkadot-launch/
  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"