version: "3.2"
services:
  imbue-1:
    container_name: imbue-1
    image: samelamin/imbue:0.9.20
    ports:
      - "9615:9615"
      - "9616:9616"
      - "9942:9942"
      - "9980:9930"
      - "31033:31033"
      - "31034:31034"
    command: bash -c "wget https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/genesis/imbue-kusama-spec.json;/imbue  --collator --unsafe-ws-external --log=xcm=debug --rpc-cors=all --rpc-external --rpc-methods=Unsafe -d /cumulus_parachain/imbue-1  --name imbue-collator-1 --ws-port 9942 --rpc-port 9930 --parachain-id 2121 --chain imbue-kusama-spec.json --execution=wasm --prometheus-external --port 31033 --  --port 31034 --chain kusama --sync warp --execution=wasm --prometheus-external --ws-max-out-buffer-capacity=99999 --ws-max-connections=200"
    volumes:
      - ./imbue_db/cumulus_parachain_1:/cumulus_parachain/


  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"
