
//! Autogenerated weights for `pallet_proposals`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `user`, CPU: `12th Gen Intel(R) Core(TM) i9-12900H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("imbue-dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/imbue
// benchmark
// pallet
// --chain=imbue-dev
// --steps=50
// --repeat=20
// --pallet=pallet_proposals
// --extrinsic=*
// --output=./pallets/proposals/src/weights.rs
// --template=./scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::WeightInfoT;

/// Weights for `pallet_proposals` using the Substrate node and recommended hardware.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfoT for WeightInfo<T> {
	/// Storage: `ImbueProposals::Projects` (r:1 w:0)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::RoundsExpiring` (r:1 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:0 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn submit_milestone() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `889`
		//  Estimated: `39920`
		// Minimum execution time: 61_006_000 picoseconds.
		Weight::from_parts(68_916_000, 39920)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:1 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::RoundsExpiring` (r:0 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn vote_on_milestone() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1069`
		//  Estimated: `39920`
		// Minimum execution time: 94_587_000 picoseconds.
		Weight::from_parts(112_360_000, 39920)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Deposits::CurrentDeposits` (r:1 w:1)
	/// Proof: `Deposits::CurrentDeposits` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::CompletedProjects` (r:1 w:1)
	/// Proof: `ImbueProposals::CompletedProjects` (`max_values`: None, `max_size`: Some(262184), added: 264659, mode: `MaxEncodedLen`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1503`
		//  Estimated: `265649`
		// Minimum execution time: 252_196_000 picoseconds.
		Weight::from_parts(300_488_000, 265649)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ImbueProposals::RoundsExpiring` (r:1 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:0 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `20036`
		// Minimum execution time: 20_005_000 picoseconds.
		Weight::from_parts(22_550_000, 20036)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:0)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectsInDispute` (r:1 w:1)
	/// Proof: `ImbueProposals::ProjectsInDispute` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ImbueDisputes::Disputes` (r:1 w:1)
	/// Proof: `ImbueDisputes::Disputes` (`max_values`: None, `max_size`: Some(6602), added: 9077, mode: `MaxEncodedLen`)
	/// Storage: `ImbueDisputes::DisputesFinaliseOn` (r:1 w:1)
	/// Proof: `ImbueDisputes::DisputesFinaliseOn` (`max_values`: None, `max_size`: Some(221), added: 2696, mode: `MaxEncodedLen`)
	fn raise_dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5118`
		//  Estimated: `39920`
		// Minimum execution time: 83_336_000 picoseconds.
		Weight::from_parts(85_489_000, 39920)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:52 w:52)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn refund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12011`
		//  Estimated: `136346`
		// Minimum execution time: 3_089_534_000 picoseconds.
		Weight::from_parts(3_135_786_000, 136346)
			.saturating_add(T::DbWeight::get().reads(53_u64))
			.saturating_add(T::DbWeight::get().writes(53_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfoT for () {
	/// Storage: `ImbueProposals::Projects` (r:1 w:0)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::RoundsExpiring` (r:1 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:0 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn submit_milestone() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `889`
		//  Estimated: `39920`
		// Minimum execution time: 61_006_000 picoseconds.
		Weight::from_parts(68_916_000, 39920)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:1 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::RoundsExpiring` (r:0 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn vote_on_milestone() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1069`
		//  Estimated: `39920`
		// Minimum execution time: 94_587_000 picoseconds.
		Weight::from_parts(112_360_000, 39920)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Deposits::CurrentDeposits` (r:1 w:1)
	/// Proof: `Deposits::CurrentDeposits` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::CompletedProjects` (r:1 w:1)
	/// Proof: `ImbueProposals::CompletedProjects` (`max_values`: None, `max_size`: Some(262184), added: 264659, mode: `MaxEncodedLen`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1503`
		//  Estimated: `265649`
		// Minimum execution time: 252_196_000 picoseconds.
		Weight::from_parts(300_488_000, 265649)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ImbueProposals::RoundsExpiring` (r:1 w:1)
	/// Proof: `ImbueProposals::RoundsExpiring` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::MilestoneVotes` (r:1 w:1)
	/// Proof: `ImbueProposals::MilestoneVotes` (`max_values`: None, `max_size`: Some(375), added: 2850, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::IndividualVoteStore` (r:1 w:1)
	/// Proof: `ImbueProposals::IndividualVoteStore` (`max_values`: None, `max_size`: Some(16571), added: 19046, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::Rounds` (r:0 w:1)
	/// Proof: `ImbueProposals::Rounds` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectInVoting` (r:0 w:1)
	/// Proof: `ImbueProposals::ProjectInVoting` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `20036`
		// Minimum execution time: 20_005_000 picoseconds.
		Weight::from_parts(22_550_000, 20036)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:0)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `ImbueProposals::ProjectsInDispute` (r:1 w:1)
	/// Proof: `ImbueProposals::ProjectsInDispute` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ImbueDisputes::Disputes` (r:1 w:1)
	/// Proof: `ImbueDisputes::Disputes` (`max_values`: None, `max_size`: Some(6602), added: 9077, mode: `MaxEncodedLen`)
	/// Storage: `ImbueDisputes::DisputesFinaliseOn` (r:1 w:1)
	/// Proof: `ImbueDisputes::DisputesFinaliseOn` (`max_values`: None, `max_size`: Some(221), added: 2696, mode: `MaxEncodedLen`)
	fn raise_dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5118`
		//  Estimated: `39920`
		// Minimum execution time: 83_336_000 picoseconds.
		Weight::from_parts(85_489_000, 39920)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ImbueProposals::Projects` (r:1 w:1)
	/// Proof: `ImbueProposals::Projects` (`max_values`: None, `max_size`: Some(36455), added: 38930, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:52 w:52)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn refund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12011`
		//  Estimated: `136346`
		// Minimum execution time: 3_089_534_000 picoseconds.
		Weight::from_parts(3_135_786_000, 136346)
			.saturating_add(RocksDbWeight::get().reads(53_u64))
			.saturating_add(RocksDbWeight::get().writes(53_u64))
	}
}