name: build-on-hosted-runner
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

    env:
      CARGO_TERM_COLOR: always

jobs:
  build-imbue-collator:
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true

      - name: Update submodules
        run: git submodule update --recursive --remote

      - name: Run tests with benchmarks
        run: cargo test --features runtime-benchmarks
  clippy:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Ensure executable
        run: chmod +x ./ci/jobs/clippy.sh
      - name: Run clippy
        run: ./ci/jobs/clippy.sh
  rustfmt:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Ensure executable
      run: chmod +x ./ci/jobs/rustfmt.sh
    - name: Run rustfmt
      run: ./ci/jobs/rustfmt.sh