name: build-on-self-hosted-runner
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
    env:
      CARGO_TERM_COLOR: always
      GCP_ZONE: europe-west3-a
#      HOME: /home/ubuntu
jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.10
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004-lts
          machine_type: e2-highcpu-32
          disk_size: 100
          machine_zone: europe-west3-a
          ephemeral: true

      - name: install as user
        run: >
          gcloud compute ssh
          gce-gh-runner-${{ github.run_id }}-${{ github.run_attempt }}
          --zone europe-west3-a
          --command="cd /actions-runner && sudo ./svc.sh uninstall && sudo ./svc.sh install ubuntu && sudo ./svc.sh start && sudo ./runsvc.sh"

  test-features:
      needs: create-runner
      runs-on: ${{ needs.create-runner.outputs.label }}
      steps:
      - uses: actions/checkout@v4

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true

      - name: Install Protobuf
        run: sudo apt install protobuf-compiler -y

      - name: 🫠 rustfmt 🫠
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Run tests with benchmarks
        run: cargo test --features runtime-benchmarks

#      - name: Delete runner VM
#        if: always()
#        run: >
#          gcloud compute instances delete
#          gce-gh-runner-${{ github.run_id }}-${{ github.run_attempt }}
#          --quiet --zone europe-west2-a
