name: test-features
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - staging
    paths-ignore:
      - "**.md"
env:
  CARGO_TERM_COLOR: always
  GCP_ZONES: (europe-central2-a, europe-central2-b, europe-central2-c, europe-north1-a, europe-north1-b, europe-north1-c, europe-west1-b, europe-west1-c)
  GCP_ZONE: ${GCP_ZONES[$((RANDOM % 8)]})

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to main from staging."
          exit 1

  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.10
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004-lts
          machine_type: e2-highcpu-16
          disk_size: 100
          machine_zone: ${{ env.GCP_ZONE }}
          ephemeral: true

  test-features:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4

      - name: Set HOME
        run: echo "HOME=/home/ubuntu" >> ${GITHUB_ENV}

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true

      - name: Install Dependencies
        run: sudo apt install protobuf-compiler clang build-essential -y

      - name: Run tests with benchmarks
        run: cargo test --features runtime-benchmarks