
name: check-branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - staging
    paths-ignore:
      - "**.md"

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to main from staging."
          exit 1