name: rust
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

    env: 
      CARGO_TERM_COLOR: always

jobs:
  build-imbue-collator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clean env
        run: ./ci/jobs/clean.sh 

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true

      - name: Update submodules
        run: git submodule update --recursive --remote

      - name: Clean unused directories
        run: sudo rm -rf /usr/share/dotnet;sudo rm -rf /opt/ghc;sudo rm -rf "/usr/local/share/boost";sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Protobuf
        run: sudo apt install protobuf-compiler

      - name: Run tests with benchmarks
        run: cargo test --features runtime-benchmarks
  clippy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Clean unused directories
        run: sudo rm -rf /usr/share/dotnet;sudo rm -rf /opt/ghc;sudo rm -rf "/usr/local/share/boost";sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Protobuf
        run: sudo apt install protobuf-compiler

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-22
          target: wasm32-unknown-unknown
          override: true
      
      - name: Install clippy
        run: rustup component add clippy
      
      - name: Ensure executable
        run: chmod +x ./ci/jobs/clippy.sh
      
      - name: Run clippy
        run: ./ci/jobs/clippy.sh
      
      - name: clean build artifacts
        run: sudo rm -rf ./target

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Ensure executable
      run: chmod +x ./ci/jobs/rustfmt.sh

    - name: Run rustfmt
      run: ./ci/jobs/rustfmt.sh