# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: coverage

jobs:
  check:
    name: imbue-test-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-12-04
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.20.1"
          args: "-- --test-threads 1"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: code-coverage-report
          path: cobertura.xml
