name: try-runtime
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - staging
    paths-ignore:
      - "**.md"
env:
  CARGO_TERM_COLOR: always
  GCP_ZONE: europe-west3-b

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.10
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004
          machine_type: e2-highcpu-32
          machine_zone: ${{ env.GCP_ZONE }}
          disk_size: 100
          ephemeral: true

  try-runtime:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4

      - name: Set HOME
        run: echo "HOME=/home/ubuntu" >> ${GITHUB_ENV}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Dependencies
        run: sudo apt install protobuf-compiler clang build-essential -y

      - name: Install try-runtime
        run: cargo install --git https://github.com/paritytech/try-runtime-cli --locked

      - name: Build binary with try-runtime
        run: cargo build --features try-runtime

      - name: run imbue kusama try-runtime
        run: try-runtime --runtime ./target/debug/wbuild/imbue-kusama-runtime/imbue_kusama_runtime.wasm on-runtime-upgrade live --uri ws://34.123.139.91:9942

      - name: run imbue rococo try-runtime
        run: try-runtime --runtime ./target/debug/wbuild/imbue-kusama-runtime/imbue_kusama_runtime.wasm on-runtime-upgrade live --uri ws://35.202.116.137:9942


